lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'apa/', index, name='index'),
]

lab_4/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
    url(r'^result_table', message_table, name='result_table'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
from django.views.generic import RedirectView
from lab_1.views import index as index_lab1

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include('lab_2_addon.urls', namespace='lab-2-addon')),
    url(r'^lab-3/', include('lab_3.urls', namespace='lab-3')),
    url(r'^lab-4/', include('lab_4.urls', namespace='lab-4')),
    url(r'^lab-5/', include('lab_5.urls', namespace='lab-5')), 
    url(r'^$', RedirectView.as_view(url='lab-4/', permanent='True')),
    url(r'^$', index_lab1, name='index'),
]

lab_4/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

lab_4/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

lab_4/views.py
from django.shortcuts import render
from lab_2.views import landing_page_content
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message


# Create your views here.
response = {'author': "Rifki"} #TODO Implement yourname
about_me = ["teriyaki god", "assian pizza", "official donald trump twitters admin", "tumblr bois", "nickelodeon girls", "meme machine"]
def index(request):
    response['content'] = landing_page_content
    html = 'lab_4/lab_4.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['about_me'] = about_me
    response['message_form'] = Message_Form
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
                          message=response['message'])
        message.save()
        html ='lab_4/form_result.html'
        return render(request, html, response)
    else:        
        return HttpResponseRedirect('/lab-4/')

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'lab_4/table.html'
    return render(request, html , response)

lab_4/templates/lab_4/partials/footer.html
{% block footer %}
    <footer id="myFooter">
        <div class="container">
            <ul>
                <li><a href="#">Company Information</a></li>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">Terms of service</a></li>
            </ul>
        <p class="footer-copyright">&copy; 2017 {{ author }} & the Wibu</p>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <a href="https://youtu.be/OLpeX4RRo28?t=114" target="_blank" style="bottom: 0; right: 0; position: fixed; margin: 0 15px 15px 0;"><img src="https://upload.wikimedia.org/wikipedia/en/8/8b/Pink_Season.jpg" style="border-radius: 50%;width: 75px;height: 75px;"></a>
    
{% endblock %}

lab_4/templates/lab_4/partials/header.html
<nav >
  <div id="navigation" class="topnav">
    <a href="{% url 'lab-4:index' %}">Home</a>
    <a href="{% url 'lab-4:index' %}#bio_landing">Biography</a>
    <a href="{% url 'lab-4:index' %}#aboutme_landing">About me</a>
    <a href="{% url 'lab-4:index' %}#form_landing">Form</a>
    <a href="{% url 'lab-4:result_table' %}"> Messages Table</a>
  </div>
</nav>